management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/krish_spring_boot_learn
    username: root
    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver